import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {extract,messageText,parseUrl,safeBiliUrl} from '../lib/parser.mjs';
import {BiliClient,safeImage,formatInfo} from '../lib/bili.mjs';
import {defaults,normalize} from '../lib/config.mjs';
import * as plugin from '../index.mjs';
const BV='BV1xx411c7mD';
const payload={code:0,data:{bvid:BV,title:'测试视频',pic:'https://i0.hdslb.com/test.jpg',owner:{name:'测试UP'},desc:'简介',duration:125,stat:{view:12000,like:123}}};
const response=j=>new Response(JSON.stringify(j),{status:200});
test('裸编号、中文标点、多链接、去重',()=>{assert.deepEqual(extract(`看看${BV}，https://www.bilibili.com/video/${BV}/?share=1 和av170001`).map(x=>x.id),[BV,'av170001']);assert.equal(extract(BV,false).length,0);});
test('拒绝伪造域名和其他站点内的 BV',()=>{for(const s of [`https://evil.com/video/${BV}`,`https://www.bilibili.com.evil.com/video/${BV}`,`https://bilibili.com@evil.com/video/${BV}`,`https://notbilibili.com/video/${BV}`])assert.equal(extract(s).length,0,s);});
test('短链、动态、直播、番剧、主页、专栏',()=>{for(const [url,type] of [['https://b23.tv/abc123','short'],['https://t.bilibili.com/123','dynamic'],['https://live.bilibili.com/blanc/123','live'],['https://www.bilibili.com/bangumi/play/ep123','ep'],['https://space.bilibili.com/123','user'],['https://www.bilibili.com/read/cv123','article']])assert.equal(parseUrl(url)?.type,type,url);});
test('结构化收藏夹优先于用户主页，扩展类型识别',()=>{const a=parseUrl('https://space.bilibili.com/123/favlist?fid=456');assert.equal(a.type,'favorite_list');assert.equal(a.id,'456');assert.equal(parseUrl('https://space.bilibili.com/123/channel/collectiondetail?sid=456').type,'channel_series');assert.equal(parseUrl('https://www.bilibili.com/cheese/play/ep123').type,'cheese_video');assert.equal(parseUrl('https://www.bilibili.com/v/topic/detail?topic_id=123').type,'topic');});
test('多个 JSON 小程序段、XML 分享和消息截断',()=>{const text=messageText({message:[{type:'json',data:{data:JSON.stringify({meta:{detail_1:{qqdocurl:`https://www.bilibili.com/video/${BV}`}}})}},{type:'json',data:{data:JSON.stringify({meta:{news:{jumpUrl:'https://b23.tv/abcd'}}})}}]});assert.equal(extract(text).length,2);assert.equal(extract(messageText({message:[{type:'xml',data:{data:'<msg url="https://b23.tv/abcd"/>'}}]}))[0].type,'short');assert(messageText({raw_message:'x'.repeat(30000)}).length<=20000);});
test('URL 与封面地址限定',()=>{for(const u of ['https://127.0.0.1/','file:///etc/passwd','https://user:pass@b23.tv/a','https://b23.tv:8443/a'])assert.equal(safeBiliUrl(u),null);assert.equal(safeImage('https://evil.com/a'),null);assert.equal(safeImage('http://i0.hdslb.com/a'),'https://i0.hdslb.com/a');});
test('短链只访问 b23，解析目标前检查域名且不发送 Cookie',async()=>{const calls=[];const c=new BiliClient({...defaults,cookie:'SESSDATA=secret'},async(url,opts)=>{calls.push({url,opts});return new Response(null,{status:302,headers:{location:`https://www.bilibili.com/video/${BV}`}});});assert.equal((await c.resolve(parseUrl('https://b23.tv/abc'))).type,'video');assert.equal(calls.length,1);assert.equal(calls[0].opts.headers.Cookie,undefined);c.close();});
test('短链外部跳转被拒绝且不发起第二次请求',async()=>{let n=0;const c=new BiliClient(defaults,async()=>{n++;return new Response(null,{status:302,headers:{location:'http://127.0.0.1/private'}});});await assert.rejects(c.resolve(parseUrl('https://b23.tv/abc')),/非 B站/);assert.equal(n,1);c.close();});
test('API 数据获取、格式化、缓存、AV/BV 规范化',async()=>{let n=0;const c=new BiliClient(defaults,async()=>{n++;return response(payload);});const [a,b]=await Promise.all([c.info(extract('av170001')[0]),c.info(extract('av170001')[0])]);assert.equal(n,1);assert.equal(a.key,`video:${BV}`);assert.equal(a,b);const s=formatInfo(a,defaults);assert.match(s,/1.2万/);assert.match(s,/2:05/);assert.match(s,/测试UP/);c.close();});
test('接口错误、HTML 响应和畸形成功响应不缓存为成功',async()=>{for(const j of [{code:-412},{code:0},{code:0,data:{}}]){const c=new BiliClient(defaults,async()=>response(j));await assert.rejects(c.info(extract(BV)[0]));assert.equal(c.cache.size,0);c.close();}const c=new BiliClient(defaults,async()=>new Response('<html>'));await assert.rejects(c.info(extract(BV)[0]),/JSON/);c.close();});
test('动态与 Opus 共享去重键',()=>assert.equal(extract('https://t.bilibili.com/123 https://www.bilibili.com/opus/123').length,1));
test('配置校验与边界',()=>{assert.equal(normalize({maxLinks:100}).maxLinks,5);assert.throws(()=>normalize({groupIds:'abc'}));assert.throws(()=>normalize({cookie:'a\nb'}));assert.throws(()=>normalize({enabled:'false'}));});
async function fixture(t,config={}){
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bili-test-'));const messages=[];
 const ctx={configPath:path.join(dir,'config.json'),pluginPath:dir,adapterName:'test',pluginManager:{config:{}},logger:{info(){},warn(){},debug(){}},actions:{async call(...args){messages.push(args);return {message_id:1};}}};
 const real=globalThis.fetch;globalThis.fetch=async()=>response(payload);
 await fs.writeFile(ctx.configPath,JSON.stringify({...defaults,...config}));await plugin.plugin_init(ctx);
 t.after(async()=>{await plugin.plugin_cleanup(ctx);globalThis.fetch=real;await fs.rm(dir,{recursive:true,force:true});});
 const event={post_type:'message',message_type:'group',self_id:99,user_id:123,group_id:456,message_id:1,message:[{type:'text',data:{text:BV}}]};
 return {ctx,event,messages};
}
test('NapCat 生命周期和四参数发送；群内冷却不影响其他群',async t=>{const {ctx,event,messages}=await fixture(t);await plugin.plugin_onmessage(ctx,event);await plugin.plugin_onmessage(ctx,{...event,message_id:2});await plugin.plugin_onmessage(ctx,{...event,group_id:789,message_id:3});assert.equal(messages.length,2);assert.equal(messages[0].length,4);assert.equal(messages[0][1].group_id,'456');assert.equal(messages[0][1].message[0].type,'image');});
test('自发消息、非消息事件、黑名单和白名单被过滤',async t=>{const {ctx,event,messages}=await fixture(t,{groupMode:'allow',groupIds:'789',blockedUsers:'321'});await plugin.plugin_onmessage(ctx,event);await plugin.plugin_onmessage(ctx,{...event,group_id:789,user_id:321});await plugin.plugin_onmessage(ctx,{...event,group_id:789,user_id:99});await plugin.plugin_onmessage(ctx,{...event,group_id:789,post_type:'message_sent'});assert.equal(messages.length,0);});
test('配置保存立即生效并可重新加载',async t=>{const {ctx,event,messages}=await fixture(t);await plugin.plugin_set_config(ctx,{enabled:false});await plugin.plugin_onmessage(ctx,event);assert.equal(messages.length,0);await plugin.plugin_cleanup(ctx);await plugin.plugin_init(ctx);assert.equal((await plugin.plugin_get_config(ctx)).enabled,false);await plugin.plugin_set_config(ctx,{enabled:true});await plugin.plugin_onmessage(ctx,event);assert.equal(messages.length,1);});
test('图片失败降级纯文字；私聊发到正确用户',async t=>{const {ctx,event,messages}=await fixture(t);ctx.actions.call=async(...args)=>{messages.push(args);if(messages.length===1)return {status:'failed',retcode:1200};return {message_id:2};};await plugin.plugin_onmessage(ctx,{...event,message_type:'private'});assert.equal(messages.length,2);assert.equal(messages[1][1].user_id,'123');assert.equal(messages[1][1].message.length,1);assert.equal(messages[1][1].message[0].type,'text');});
test('并发相同链接只回复一次',async t=>{const {ctx,event,messages}=await fixture(t);await Promise.all([plugin.plugin_onmessage(ctx,event),plugin.plugin_onmessage(ctx,{...event,message_id:2})]);assert.equal(messages.length,1);});
test('卸载中止请求并禁止随后发送',async t=>{const {ctx,event,messages}=await fixture(t);let release,started;const ready=new Promise(r=>started=r);globalThis.fetch=async()=>{started();await new Promise(r=>release=r);return response(payload);};await plugin.plugin_init(ctx);const task=plugin.plugin_onmessage(ctx,event);await ready;await plugin.plugin_cleanup(ctx);release();await task;assert.equal(messages.length,0);});
